import torch
import os

FAKE_DIR = "dataset/fake"
os.makedirs(FAKE_DIR, exist_ok=True)

SENTENCES = [
    "The weather today is bright and sunny with a gentle breeze.",
    "I am currently working on a project about voice detection technology.",
    "Artificial intelligence is changing the way we live and work.",
    "Please remember to submit your assignment before the deadline.",
    "The train to the city departs every hour from platform two.",
    "She enjoys reading books about science and history.",
    "Our team meeting has been rescheduled to next Monday morning.",
    "The recipe requires two cups of flour and a pinch of salt.",
    "Technology continues to evolve at a rapid and exciting pace.",
    "He walked quietly through the park enjoying the evening air.",
    "The new software update improves performance and battery life.",
    "Students are encouraged to ask questions during the lecture.",
    "The market was filled with fresh fruits and colorful vegetables.",
    "We need to finish the report before the end of the week.",
    "The mountains looked beautiful covered in fresh white snow.",
    "Could you please send me the file by tomorrow afternoon.",
    "The conference will be held online due to travel restrictions.",
    "A balanced diet and regular exercise keep the body healthy.",
    "The museum exhibit features paintings from the modern era.",
    "Traffic was heavy this morning because of the road construction.",
    "Hello, how are you doing today? I hope everything is fine.",
    "This is a sample sentence used for testing voice detection.",
    "The sun rises in the east and sets in the west every day.",
    "Learning new skills can open many doors in your career.",
    "The library remains open until nine in the evening on weekdays.",
    "Bank robbers usually plan their escape route in advance.",
    "The company announced a new policy for remote employees.",
    "My phone battery drains faster than it used to last year.",
    "The chef prepared a delicious meal using fresh local ingredients.",
    "Scientists discovered a new species of butterfly in the rainforest.",
    "The football match was postponed due to heavy rainfall.",
    "Please verify your account details before proceeding further.",
    "The children played happily in the garden all afternoon.",
    "Electric vehicles are becoming more popular around the world.",
    "The doctor advised him to rest and drink plenty of fluids.",
    "Our flight got delayed because of bad weather conditions.",
    "The bakery down the street sells the best chocolate cake.",
    "He forgot his umbrella at home despite the forecast for rain.",
    "The company's stock price rose sharply after the announcement.",
    "I usually wake up early to go for a morning jog.",
    "The teacher explained the concept using simple everyday examples.",
    "Renewable energy sources are essential for a sustainable future.",
    "The city council approved the plan for a new public park.",
    "Please hold the line while I transfer your call.",
    "The novel tells the story of a young girl's journey home.",
    "Security cameras were installed around the building last week.",
    "The orchestra performed beautifully at the concert hall tonight.",
    "Remember to update your password every few months for safety.",
    "The volcano has been dormant for over a hundred years.",
    "Our customer support team is available around the clock.",
    "The garden was full of blooming roses and tulips.",
    "He spent the weekend fixing the old wooden fence.",
    "The airport was crowded during the holiday travel season.",
    "This document contains confidential information about the project.",
    "The puppy chased its tail around the living room.",
    "Investors are cautious about the current market volatility.",
    "The professor assigned a research paper due next month.",
    "A gentle rain fell over the quiet village all night.",
    "The bridge was closed for repairs after the storm damage.",
    "Please enter your one time password to complete the transaction.",
    "The hikers reached the summit just before sunset.",
    "Our new office is located near the central train station.",
    "The bakery smells wonderful early in the morning.",
    "He plays the guitar every evening after finishing his work.",
    "The committee will review the proposal next Thursday.",
    "The lake was calm and reflected the colors of the sky.",
    "This application requires a stable internet connection to function.",
    "The farmer harvested the wheat before the first frost arrived.",
    "Please keep your seatbelt fastened during the flight.",
    "The artist spent months painting the mural downtown.",
    "Our subscription plan includes unlimited access to all features.",
    "The storm knocked down several trees along the highway.",
    "She practices yoga every morning to stay calm and focused.",
    "The bank requires additional verification for large transactions.",
    "The festival attracts thousands of visitors from around the country.",
    "Please double check your email address before submitting the form.",
    "The old castle stood on a hill overlooking the valley.",
    "He recently switched careers to pursue his passion for photography.",
    "The government announced new measures to reduce pollution.",
    "The soup needs a little more salt and pepper.",
    "Our warranty covers any manufacturing defects for two years.",
    "The astronauts spent six months aboard the space station.",
    "The library added several new titles to its collection.",
    "This offer is valid only for a limited time.",
    "The children built a sandcastle on the beach yesterday.",
    "The engineer inspected the bridge for structural damage.",
    "Please contact customer service if you have any questions.",
    "The orchestra will perform a new symphony this weekend.",
    "The startup secured funding from several major investors.",
    "The wind picked up speed as the storm approached the coast.",
    "Our team worked overtime to meet the project deadline.",
    "The zoo introduced two new baby elephants this spring.",
    "Please remember to back up your files regularly.",
    "The chef garnished the dish with fresh herbs.",
    "The satellite transmitted images of the distant planet.",
    "The negotiations lasted several hours before reaching an agreement.",
    "The garden gnome had been in the family for generations.",
    "Please review the terms and conditions before you continue.",
    "The marathon route passes through five different neighborhoods.",
    "The professor's lecture covered the history of ancient civilizations.",
    "The company launched a new product line last quarter.",
    "The river flooded several fields after days of heavy rain.",
    "Please keep your voice down in the reading room.",
    "The mechanic replaced the brakes and changed the oil.",
    "The painting sold for a record price at the auction.",
    "Our flight departs at six in the morning tomorrow.",
    "The scientist published her findings in a leading journal.",
    "The bakery introduced a new flavor of croissant this month.",
    "Please sign the document at the bottom of the page.",
    "The city installed new streetlights along the main avenue.",
    "The hiking trail offers stunning views of the valley below.",
    "Our team is analyzing customer feedback from the last survey.",
    "The comedian had the entire audience laughing all night.",
    "Please avoid sharing your password with anyone else.",
    "The construction crew finished the building ahead of schedule.",
    "The violinist practiced for hours before the big performance.",
    "The airline offers complimentary snacks on long flights.",
    "The researcher collected samples from the ocean floor.",
    "Please check the weather forecast before planning your trip.",
    "The bakery closes early on Sundays.",
    "The committee approved the budget for next year.",
    "The gardener trimmed the hedges along the front yard.",
    "The software crashed unexpectedly during the presentation.",
    "Please make sure the door is locked before you leave.",
    "The chef added a splash of lemon juice for extra flavor.",
    "The satellite launch was delayed due to technical issues.",
    "Our office will be closed for the public holiday.",
    "The children learned about the solar system in class today.",
    "The novelist spent three years writing her latest book.",
    "Please arrive fifteen minutes early for your appointment.",
    "The factory increased production to meet growing demand.",
    "The lighthouse guided ships safely into the harbor.",
    "Our team celebrated the successful launch of the new app.",
    "The recipe calls for fresh basil and ripe tomatoes.",
    "The airport announced new security procedures for travelers.",
    "Please update your billing information to avoid service interruption.",
    "The choir rehearsed for weeks before the holiday concert.",
    "The engineer designed a more efficient cooling system.",
    "The park was quiet except for the sound of birds singing.",
    "Please keep your receipt in case you need a refund.",
    "The volcano erupted after months of increasing activity.",
    "Our company values honesty and transparency in every decision.",
    "The tailor adjusted the suit to fit perfectly.",
    "The river winds through the valley before reaching the sea.",
    "Please charge your device fully before the long flight.",
    "The teacher praised the students for their hard work.",
    "The bakery uses only organic ingredients in its bread.",
    "Our new website launches next Friday with several improvements.",
    "The photographer captured a stunning image of the sunset.",
    "Please remember to renew your subscription before it expires.",
    "The farmer planted rows of corn across the field.",
    "The museum offers free admission on the first Sunday of each month.",
    "Our support line is open twenty four hours a day.",
    "The chef trained for years in a famous culinary school.",
    "The satellite orbits the earth once every ninety minutes.",
    "Please review your order summary before completing the purchase.",
    "The orchestra tuned their instruments before the performance began.",
    "The company expanded its operations into three new countries.",
    "The gardener planted tulips along the walkway this spring.",
    "Please contact us if you experience any technical difficulties.",
    "The pilot announced a slight delay due to air traffic.",
    "The scientist explained the results of the recent experiment.",
    "Our team is committed to delivering quality work on time.",
    "The bakery's ovens have been running since early morning.",
    "The hikers followed the trail markers to the summit.",
    "Please ensure all documents are signed before the meeting.",
    "The city plans to build a new bridge over the river.",
    "The violin solo was the highlight of the evening.",
    "Our warranty does not cover accidental damage to the device.",
    "The chef recommended pairing the dish with a light white wine.",
    "The researchers are studying the effects of climate change.",
    "Please keep this information confidential until further notice.",
    "The airport shuttle runs every twenty minutes throughout the day.",
    "The novelist drew inspiration from her childhood memories.",
    "Our team will present the findings at next week's meeting.",
    "The gardener watered the plants early in the morning.",
    "Please verify your identity before accessing your account.",
    "The factory upgraded its equipment to improve efficiency.",
    "The choir sang beautifully during the holiday celebration.",
    "The engineer calculated the load capacity of the new bridge.",
    "Our office relocated to a larger building downtown.",
    "The recipe suggests baking the bread for forty five minutes.",
    "Please double check the spelling of your name on the form.",
    "The lighthouse keeper lived alone on the small island.",
    "The barista prepared a fresh cup of coffee for the customer.",
    "Our flight was rebooked after the original one was cancelled.",
    "The students gathered in the auditorium for the morning assembly.",
    "Please remember to switch off the lights before leaving the office.",
    "The fisherman returned to the harbor just before the storm hit.",
    "The magazine published an article about sustainable farming practices.",
    "Our team brainstormed several ideas for the upcoming campaign.",
    "The tour guide explained the history of the ancient temple.",
    "Please fasten your seatbelt as we prepare for takeoff.",
    "The librarian organized the books by genre and author.",
    "The startup's revenue doubled within the first year of launch.",
    "Please water the plants twice a week during the summer.",
    "The detective examined the evidence carefully before drawing conclusions.",
    "Our new policy allows employees to work from home two days a week.",
    "The bakery introduced gluten free options for its customers.",
    "The astronomer observed the meteor shower through his telescope.",
]


device = torch.device("cpu")
model, example_text = torch.hub.load(
    repo_or_dir="snakers4/silero-models",
    model="silero_tts",
    language="en",
    speaker="v3_en"
)
model.to(device)

speakers = ["en_0", "en_1", "en_2", "en_3", "en_4", "en_5", "en_6", "en_7", "en_8", "en_9", "en_10", "en_11", "en_12", "en_13", "en_14", "en_15", "en_16", "en_17", "en_18", "en_19", "en_20", "en_21", "en_22", "en_23", "en_24", "en_25", "en_26", "en_27", "en_28", "en_29", "en_30", "en_31", "en_32", "en_33", "en_34", "en_35", "en_36", "en_37", "en_38", "en_39", "en_40", "en_41", "en_42", "en_43", "en_44", "en_45", "en_46", "en_47", "en_48", "en_49", "en_50", "en_51", "en_52", "en_53", "en_54", "en_55", "en_56", "en_57", "en_58", "en_59", "en_60", "en_61", "en_62", "en_63", "en_64", "en_65", "en_66", "en_67", "en_68", "en_69", "en_70", "en_71", "en_72", "en_73", "en_74", "en_75", "en_76", "en_77", "en_78", "en_79", "en_80", "en_81", "en_82", "en_83", "en_84", "en_85", "en_86", "en_87", "en_88", "en_89", "en_90", "en_91", "en_92", "en_93", "en_94", "en_95", "en_96", "en_97", "en_98", "en_99", "en_100"]

def get_next_index(folder, prefix):
    existing = [f for f in os.listdir(folder) if f.startswith(prefix) and f.endswith(".wav")]
    nums = [int(f.replace(prefix, "").replace(".wav", "")) for f in existing if f.replace(prefix, "").replace(".wav", "").isdigit()]
    return max(nums) + 1 if nums else 1

start_idx = get_next_index(FAKE_DIR, "fake_")

count = 0
for i, text in enumerate(SENTENCES * 20):
    idx = start_idx + i
    filepath = os.path.join(FAKE_DIR, f"fake_{idx}.wav")
    speaker = speakers[i % len(speakers)]
    try:
        model.save_wav(text=text, speaker=speaker, sample_rate=24000, audio_path=filepath)
        count += 1
        print(f"Saved fake_{idx}.wav using {speaker}")
    except Exception as e:
        print(f"Failed fake_{idx}.wav: {e}")

print(f"Done! Generated {count} files.")